app/main/forms.py
# import flask_wtf
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, TextAreaField, BooleanField, DateTimeField, IntegerField, FloatField
from wtforms.validators import ValidationError, DataRequired, Length



class TaskForm(FlaskForm):
    task_desc = StringField('task_desc', validators=[DataRequired()])
    task_status_completed = SelectField('Status', choices=[('todo','Todo'),('doing','Doing'),('done','Done')])
    submit = SubmitField('submit')

class AppointmentForm(FlaskForm):
    appointment_title = StringField('Appointment Title', validators=[DataRequired()])
    appointment_start_date = DateTimeField('Start Time', validators=[DataRequired()])
    appointment_duration = StringField('Duration', validators=[DataRequired()])
    appointment_location = StringField('Customer Address', validators=[DataRequired()])
    customer_name = StringField('Customer Name', validators=[DataRequired()])
    customer_notes = StringField('Customer Notes', validators=[DataRequired()])
    submit = SubmitField ('Add')

class SearchForm(FlaskForm):
    search = StringField('Search')
    submit = SubmitField('submit')

app/main/__init__.py
# Imports the Blueprint class from flask.
from flask import Blueprint

bp = Blueprint('main',__name__)

from app.main import routes

app/main/routes.py
from flask import render_template,  redirect, url_for
from app.main import bp
from app import db
from app.main.forms import TaskForm, AppointmentForm, SearchForm
from app.models import Task, Appointment
from datetime import datetime
from datetime import datetime as dt



# Main route of the applicaitons.
@bp.route('/', methods=['GET','POST'])
def index():
    return render_template("main/index.html")


#
#  Route for viewing and adding new tasks.
@bp.route('/todolist', methods=['GET','POST'])
def todolist():
    form = TaskForm()

    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.
        new_task = Task()
        new_task.task_desc =  form.task_desc.data
        new_task.task_status = form.task_status_completed.data

        db.session.add(new_task)
        db.session.commit()

        # Redirect to this handler - but without form submitted - gets a clear form.
        return redirect(url_for('main.todolist'))

    todo_list = db.session.query(Task).all()

    return render_template("main/todolist.html",todo_list = todo_list,form= form)


#
# Route for removing a task
@bp.route('/todolist/remove/<int:task_id>', methods=['GET','POST'])
def remove_task(task_id):

    # Query database, remove items
    Task.query.filter(Task.task_id == task_id).delete()
    db.session.commit()

    return redirect(url_for('main.todolist'))


#
# Route for editing a task

@bp.route('/todolist/edit/<int:task_id>', methods=['GET','POST'])
def edit_task(task_id):
    form = TaskForm()
    print(form.validate_on_submit())
    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.

        current_task = Task.query.filter_by(task_id=task_id).first_or_404()
        current_task.task_desc =  form.task_desc.data
        current_task.task_status = form.task_status_completed.data

        db.session.add(current_task)
        db.session.commit()
        # After editing, redirect to the view page.
        return redirect(url_for('main.todolist'))

    # get task for the database.
    current_task = Task.query.filter_by(task_id=task_id).first_or_404()

    # update the form model in order to populate the html form.
    form.task_desc.data =     current_task.task_desc
    form.task_status_completed.data = current_task.task_status

    return render_template("main/todolist_edit_view.html",form=form, task_id = task_id)


#
#  Route for viewing and adding new tasks.
@bp.route('/appointmentlist/<int:sortby>/', methods=['GET','POST'])
def appointmentlist(sortby):
    form = AppointmentForm()

    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.
        new_appointment = Appointment(appointment_title=form.appointment_title.data,
                                      appointment_start_date=form.appointment_start_date.data,
                                      appointment_duration=form.appointment_duration.data,
                                      appointment_location=form.appointment_location.data,
                                      customer_name=form.customer_name.data,
                                      customer_notes=form.customer_notes.data)

        db.session.add(new_appointment)
        db.session.commit()
        # Redirect to this handler - but without form submitted - gets a clear form.
        return redirect(url_for('main.appointmentlist', sortby=sortby))

    if sortby==0:
        appointment_list = Appointment.query.order_by(Appointment.appointment_title)
    elif sortby==1:
        appointment_list = Appointment.query.order_by(Appointment.appointment_start_date)
    elif sortby==2:
        appointment_list = Appointment.query.order_by(Appointment.appointment_duration)
    elif sortby==3:
        appointment_list = Appointment.query.order_by(Appointment.appointment_location)
    elif sortby==4:
        appointment_list = Appointment.query.order_by(Appointment.customer_name)
    elif sortby==5:
        appointment_list = Appointment.query.order_by(Appointment.customer_notes)
    else:
        appointment_list = db.session.query(Appointment).all()
    return render_template("main/appointmentlist.html",appointment_list = appointment_list,form= form, sortby=sortby)



@bp.route('/appointmentlist/remove/<int:appointment_id>', methods=['GET','POST'])
def remove_appointment(appointment_id):
    # Query database, remove items
    print(appointment_id)
    Appointment.query.filter(Appointment.appointment_id == appointment_id).delete()
    db.session.commit()
    return redirect(url_for('main.appointmentlist', sortby=0))

@bp.route('/appointment/<int:appointment_id>', methods=['GET','POST'])
def appointment(appointment_id):
    form = AppointmentForm()
    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.
        modified_appointment = Appointment(appointment_title=form.appointment_title.data,
                                      appointment_start_date=form.appointment_start_date.data,
                                      appointment_duration = form.appointment_duration.data,
                                      appointment_location = form.appointment_location.data,
                                      customer_name = form.customer_name.data,
                                      customer_notes = form.customer_notes.data)
        Appointment.query.filter(Appointment.appointment_id == appointment_id).delete()
        db.session.commit()
        db.session.add(modified_appointment)
        db.session.commit()

    appointment=Appointment.query.filter(Appointment.appointment_id == appointment_id).one()
    return render_template("main/ScheduleAppointment.html", appointment = appointment, form= form, appointment_id=appointment_id)

@bp.route('/appointmentsearch/<int:filterby>', methods=['GET','POST'])
def search_appointment(filterby):
    def sameDay(now,specificAppointmentTime):
        #print(specificAppointmentTime.year, now.year, specificAppointmentTime.month,now.month, specificAppointmentTime.day,now.day)
        return specificAppointmentTime.year==now.year and specificAppointmentTime.month==now.month and specificAppointmentTime.day==now.day
    def sameWeek(now,specificAppointmentTime):
        #print(now.isocalendar()[1], specificAppointmentTime.isocalendar()[1], now.year, specificAppointmentTime.year)
        return now.isocalendar()[1]==specificAppointmentTime.isocalendar()[1] and now.year==specificAppointmentTime.year

    appointment_list = Appointment.query.all()
    now = datetime.now()


    if filterby==0:#No Filter
        print('No Filter')
    elif filterby==1:#Filter for today
        for appointment in reversed(appointment_list):#if not reversed, array will skip certian items when removed
            if not sameDay(now, appointment.appointment_start_date):
                appointment_list.remove(appointment)
    elif filterby==2:#Filter for this week
        for appointment in reversed(appointment_list):#if not reversed, array will skip certian items when removed
            if not sameWeek(now, appointment.appointment_start_date):
                appointment_list.remove(appointment)
    elif filterby==3:#Filter Overdue (Everything before current datetime)
        for appointment in reversed(appointment_list):#if not reversed, array will skip certian items when removed
            if appointment.appointment_start_date>now:
                appointment_list.remove(appointment)
    else:
        print('No Filter')

    #filters based on what user is searching for
    search=''
    form = SearchForm()
    if form.validate_on_submit():
        search=form.search.data
        if search != '':
            for appointment in reversed(appointment_list):
                if search in appointment.customer_name or search in appointment.appointment_title:
                    print(search, 'found')
                else:
                    appointment_list.remove(appointment)

    count = len(appointment_list)
    return render_template("main/appointmentsearch.html",appointment_list = appointment_list, filterby=filterby,search=search, count=count, form=form)

app/templates/main/ScheduleAppointment.html
{% extends "menu.html" %}
{% block main_content %}


<link rel="stylesheet", type="text/css", href="{{url_for('static', filename='css/dropdownButton.css')}}">


<div class="page-content page-container" id="page-content"  class="align-content-center">

<div class="padding">

 <div class="row container d-flex justify-content-center">

      <div class="col-lg-12">

          <div class="card px-3">

<h4 class="card-header" class="container-fluid" > Appointment {{appointment.appointment_title}}</h4>


<span><b>Start Date:</b> '{{appointment.appointment_start_date}}'</span>

<span><b>Duration:</b> '{{appointment.appointment_duration}}'</span>

<span><b>Location:</b> '{{appointment.appointment_location}}'</span>

<span><b>Customer Name:</b> '{{appointment.customer_name}}'</span>

<span><b>Notes:</b> '{{appointment.customer_notes}}'</span>


 <a href="{{url_for('main.remove_appointment', appointment_id=appointment.appointment_id)}}">Delete</a>

                </div>



 <div class="card px-3" class="container-fluid">

                    <h4 class="card-header"> Modify Appointment</h4>

                     <form action="{{url_for('main.appointment', appointment_id=appointment.appointment_id)}}" method="POST" novalidate>
                    {{form.hidden_tag()}}
                    <p>
                        {{form.appointment_title.label}}<br>
                        {{form.appointment_title(size=100, placeholder="Cleaning, Repair, Installation", value=appointment.appointment_title)}}<br>
                        {% for error in form.appointment_title.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.appointment_start_date.label}}<br>
                        {{form.appointment_start_date(size=100, placeholder="DateTime Type eg. '2019-12-04 15:00:00'", value=appointment.appointment_start_date)}}<br>
                        {% for error in form.appointment_start_date.errors %}
                        <span style="color: red;">[{{ error }} Or wrong data type.]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.appointment_duration.label}}<br>
                        {{form.appointment_duration(size=100, placeholder="Duration", value=appointment.appointment_duration)}}<br>
                        {% for error in form.appointment_duration.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.appointment_location.label}}<br>
                        {{form.appointment_location(size=100, placeholder="Address", value=appointment.appointment_location)}}<br>
                        {% for error in form.appointment_location.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.customer_name.label}}<br>
                        {{form.customer_name(size=100, placeholder="Customer Name", value=appointment.customer_name) }}<br>
                        {% for error in form.customer_name.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.customer_notes.label}}<br>
                        {{form.customer_notes(size=100, placeholder="Notes", value=appointment.customer_notes)}}
                        {% for error in form.customer_notes.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>

                      <p><input type=submit  value="Modify" class="btn btn-primary btn-lg btn-block"> </p>



                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/appointment.html
{% extends "menu.html" %}

{% block main_content %}
<link rel="stylesheet", type="text/css", href="{{url_for('static', filename='css/dropdown.css')}}">
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <h4>CUS1166 - Appointment - {{appointment.appointment_title}}</h4>
                    <span><b>Start Date:</b> '{{appointment.appointment_start_date}}'</span>
                    <span><b>Duration:</b> '{{appointment.appointment_duration}}'</span>
                    <span><b>Location:</b> '{{appointment.appointment_location}}'</span>
                    <span><b>Customer Name:</b> '{{appointment.customer_name}}'</span>
                    <span><b>Notes:</b> '{{appointment.customer_notes}}'</span>
                    <a href="{{url_for('main.remove_appointment', appointment_id=appointment.appointment_id)}}">Delete</a>
                </div>
                <div class="card px-3">
                    <h4>CUS1166 - Modify Appointment</h4>
                    <form action="{{url_for('main.appointment', appointment_id=appointment.appointment_id)}}" method="POST" novalidate>
                    {{form.hidden_tag()}}
                    <p>
                        {{form.appointment_title.label}}<br>
                        {{form.appointment_title(size=40, placeholder="(String Type)", value=appointment.appointment_title)}}<br>
                        {% for error in form.appointment_title.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.appointment_start_date.label}}<br>
                        {{form.appointment_start_date(size=40, placeholder="(DateTime Type eg. '2019-12-04 15:00:00')", value=appointment.appointment_start_date)}}<br>
                        {% for error in form.appointment_start_date.errors %}
                        <span style="color: red;">[{{ error }} Or wrong data type.]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.appointment_duration.label}}<br>
                        {{form.appointment_duration(size=40, placeholder="(String Type)", value=appointment.appointment_duration)}}<br>
                        {% for error in form.appointment_duration.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.appointment_location.label}}<br>
                        {{form.appointment_location(size=40, placeholder="(String Type)", value=appointment.appointment_location)}}<br>
                        {% for error in form.appointment_location.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.customer_name.label}}<br>
                        {{form.customer_name(size=40, placeholder="(String Type)", value=appointment.customer_name) }}<br>
                        {% for error in form.customer_name.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.customer_notes.label}}<br>
                        {{form.customer_notes(size=40, placeholder="(String Type)", value=appointment.customer_notes)}}
                        {% for error in form.customer_notes.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p><input type="submit", value="Modify"></p>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/appointmentlist.html
{% extends "menu.html" %}

{% block main_content %}
<link rel="stylesheet", type="text/css", href="{{url_for('static', filename='css/dropdownButton.css')}}">
<div class="page-content page-container" id="page-content" class="align-content-center" >

       <div class="row container d-flex justify-content-center">

      <div class="col-lg-12">

           <div class="card px-3">
                <div class="dropdown">

                  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sort By</button> <br>
                  <div class="dropdown-content">
                    <a href="{{url_for('main.appointmentlist', sortby=0)}}">Appointment Title</a>
                    <a href="{{url_for('main.appointmentlist', sortby=1)}}">Start Date</a>
                    <a href="{{url_for('main.appointmentlist', sortby=2)}}">Duration</a>
                    <a href="{{url_for('main.appointmentlist', sortby=3)}}">Location</a>
                    <a href="{{url_for('main.appointmentlist', sortby=4)}}">Customer Name</a>
                    <a href="{{url_for('main.appointmentlist', sortby=5)}}">Customer Notes</a>
                  </div>
                </div>
                <div class="card px-3">
                    <h4 class="card-header">Appointment List</h4> <br>

                    {% for appointment in appointment_list %}

                        <a href="{{url_for('main.appointment', appointment_id=appointment.appointment_id)}}">

                             <i class="fas fa-edit">{{appointment.appointment_title}}</i>
                        </a>
                        {% if sortby == 1 %}
                          <span class="badge badge-success">>Start Date: {{appointment.appointment_start_date}}</span>
                        {% elif sortby == 2 %}
                          <span class="badge badge-success">>Duration: {{appointment.appointment_duration}}</span>
                        {% elif sortby == 3 %}
                          <span class="badge badge-success">Location: {{appointment.appointment_location}}</span>
                        {% elif sortby == 4 %}
                          <span class="badge badge-success">Customer Name: {{appointment.customer_name}}</span>
                        {% elif sortby == 5 %}
                          <span  class="badge badge-success">Notes: {{appointment.customer_notes}}</span>
                        {% endif %}

                        <a href="{{url_for('main.remove_appointment', appointment_id=appointment.appointment_id)}}" >Delete</a>





                        <br>
                    {% endfor %}
                </div>
                <div class="card px-3" class="card-header">
                  <a href="{{url_for('main.search_appointment', filterby=0)}}">Search & Filter List</a>
                </div>
                <div class="card px-3" >
                    <h4 class="card-header">Add Appointment</h4> <br>

                    <form action="{{url_for('main.appointmentlist', sortby=0)}}" method="POST" novalidate>
                    {{form.hidden_tag()}}
                    <p>
                        {{form.appointment_title.label}}<br>
                        {{form.appointment_title(size=100, placeholder="Cleaning, Repair, Installation")}}<br>
                        {% for error in form.appointment_title.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.appointment_start_date.label}}<br>
                        {{form.appointment_start_date(size=100, placeholder=" eg. '2019-12-04 15:00:00' ")}}<br>
                        {% for error in form.appointment_start_date.errors %}
                        <span style="color: red;">[{{ error }} Or wrong data type.]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.appointment_duration.label}}<br>
                        {{form.appointment_duration(size=100, placeholder="20,30,60 Minutes")}}<br>
                        {% for error in form.appointment_duration.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.appointment_location.label}}<br>
                        {{form.appointment_location(size=100, placeholder="eg. 47-300 212th St, Queens")}}<br>
                        {% for error in form.appointment_location.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.customer_name.label}}<br>
                        {{form.customer_name(size=100, placeholder=" eg. David Guetta") }}<br>
                        {% for error in form.customer_name.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>
                    <p>
                        {{form.customer_notes.label}}<br>
                        {{form.customer_notes(size=100, placeholder="Notes")}}
                        {% for error in form.customer_notes.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                        {% endfor %}
                    </p>


                        <p><input type=submit class="btn btn-primary btn-lg btn-block"> </p>

                       </form> </div> </div> </div> </div> </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/appointmentsearch.html
{% extends "menu.html" %}

{% block main_content %}
<link rel="stylesheet", type="text/css", href="{{url_for('static', filename='css/dropdownButton.css')}}">

<div class="page-content page-container" id="page-content" class="align-content-lg-center" >

    <div class="padding">

     <div class="row container d-flex justify-content-center">

      <div class="col-lg-12">

           <div class="card px-5">

                <div class="dropdown">

                  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Filter By</button> <br>

                  <div class="dropdown-content">


                     <a href="{{url_for('main.search_appointment', filterby=0)}}">Completed</a>

                    <a href="{{url_for('main.search_appointment', filterby=1)}}">Today</a>

                    <a href="{{url_for('main.search_appointment', filterby=2)}}">This Week</a>

                    <a href="{{url_for('main.search_appointment', filterby=3)}}">Overdue</a>
                  </div>
                </div>

                <form action="{{url_for('main.search_appointment', filterby=filterby)}}" method="POST" novalidate>

                  {{form.hidden_tag()}}
                  <p>
                  {{form.search(size=40, placeholder="(Search for Name or Title)")}}

                    <input type="submit" value="Search" class="btn btn-primary">



                  </p>
                </form>

                <div class="card px-3">
                    <h4>Appointment List
                      {% if filterby == 0 %}
                        <span>(Unfiltered)</span>
                      {% elif filterby == 1 %}
                        <span>(Today)</span>
                      {% elif filterby == 2 %}
                        <span>(This Week)</span>
                      {% elif filterby == 3 %}
                        <span>(Overdue)</span>
                      {% else %}
                        <span>(Completed)</span>
                      {% endif %}
                    </h4>
                    <span>Number of Search Results: {{count}}</span>

                    {% for appointment in appointment_list %}

                        <a href="{{url_for('main.appointment', appointment_id=appointment.appointment_id)}}">

                             <i class="fas fa-edit">{{appointment.appointment_title}}</i>
                        </a>
                        <span>Date: {{appointment.appointment_start_date}}</span>
                        <br>
                    {% endfor %}
                </div>


            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends "menu.html" %}

{% block main_content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="mt-5">Individual Project for CUS1166 -</h1>
      <p class="lead">Get ready to showcase your Software Engineering Skills!</p>
      <ul class="list-unstyled">
        <li> Applying agile methodoloies in software development </li>
        <li>Realizing a full sprint implementing use-case  </li>
        <li> Using Flask, ORMs, Forms to implement new features </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

app/templates/main/todolist.html
{% extends "menu.html" %}

{% block main_content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - Todo List</h4>
                        <form method="POST" action="{{url_for('main.todolist')}}" >

                        <div class="add-items d-flex">
                                <!-- csrf_token is required to validate the form -->
                                {{ form.csrf_token }}
                                {{ form.task_desc(class_='form-control todo-list-input', placeholder='What do you need to do today?')}}
                                {{ form.task_status_completed }}
                                <button class="add btn btn-primary font-weight-bold todo-list-add-btn">Add</button>
                       </div>
                     </form>

                       <!-- Show current tasks if avaiblae -->
                        <div class="list-wrapper">
                            <ul class="d-flex flex-column-reverse todo-list">
                             {% for task in todo_list %}

                                {% if 'done' == task.task_status%}
                                    <li class="completed">
                                {% else %}
                                    <li>
                                {% endif %}
                                    <a href="{{url_for('main.edit_task',task_id=task.task_id)}}">
                                         <i class="fas fa-edit"></i>
                                    </a>

                                    <div class="form-check">

                                      <label class="form-check-label">
                                          {% if 'done' == task.task_status %}
                                            {{task.task_desc}} - <span class="badge badge-success">{{task.task_status}}</span>
                                          {% elif 'doing' == task.task_status %}
                                            {{task.task_desc}} - <span class="badge badge-warning">{{task.task_status}}</span>
                                          {% elif 'todo' == task.task_status %}
                                             {{task.task_desc}} - <span class="badge badge-danger">{{task.task_status}}</span>
                                          {% endif %}
                                            <i class="input-helper"></i>
                                      </label>
                                    </div>
                                    <a href="{{url_for('main.remove_task',task_id=task.task_id)}}" class="remove"><i class="fas fa-times"></i></a>
                              </li>
                             {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main/todolist_edit_view.html
{% extends "menu.html" %}

{% block content %}
<div class="page-content page-container" id="page-content">

<div class="padding">

<div class="row container d-flex justify-content-center">

 <div class="col-lg-15">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - Todo List</h4>

                        <form method="POST" action="{{url_for('main.edit_task',task_id=task_id)}}" >

                            <div class="add-items d-flex">

                                <!-- csrf_token is required to validate the form -->
                                {{ form.csrf_token }}
                                {{ form.task_desc(class_='form-control todo-list-input', placeholder='What do you need to do today?')}}
                                {{ form.task_status_completed }}
                                <button class="add btn btn-primary font-weight-bold todo-list-add-btn">Add</button>
                       </div>
                     </form>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}